import { IApplication } from '../models/application.model';
import {
  getHygieneChecklistForBusiness,
  VALID_HYGIENE_ITEM_IDS,
  HygieneChecklistItem,
} from '../rules/hygiene.rules';
import { AppError } from '../utils/appError';
import { UploadDocumentInput } from '../validators/hygiene.validator';

export class HygieneService {
  /**
   * Verify eligibility has been checked prior to hygiene generation
   */
  static verifyEligibilityChecked(application: IApplication): void {
    const eligibleStatuses = [
      'ELIGIBILITY_CHECKED',
      'HYGIENE_GENERATED',
      'PAYMENT_PENDING',
      'PAYMENT_SIMULATED',
      'PASS_GENERATED',
      'COMPLETED',
    ];

    if (!eligibleStatuses.includes(application.status)) {
      throw AppError.badRequest(
        'Hygiene checklist is unavailable before eligibility has been evaluated. Please complete business review and eligibility check first.'
      );
    }
  }

  /**
   * Retrieve the controlled hygiene checklist for an application
   */
  static getChecklist(application: IApplication) {
    this.verifyEligibilityChecked(application);

    const checklist = getHygieneChecklistForBusiness(
      application.businessDetails?.stallType
    );

    const completedSet = new Set(application.hygieneChecklist?.completedItems || []);

    const items = checklist.map((item) => ({
      id: item.id,
      title: item.title,
      description: item.description,
      category: item.category,
      mandatory: item.mandatory,
      compliant: completedSet.has(item.id),
    }));

    return {
      applicationId: application._id.toString(),
      isPrototype: true,
      items,
      overallScore: application.hygieneChecklist?.overallScore ?? 0,
      status: application.status,
    };
  }

  /**
   * Submit and persist completed hygiene checklist items
   */
  static async completeChecklist(
    application: IApplication,
    input: string[] | {
      completedItemIds?: string[];
      passed?: boolean;
      confidenceScore?: number;
      markers?: NonNullable<IApplication['hygieneAudit']>['markers'];
      summary?: string;
    }
  ) {
    this.verifyEligibilityChecked(application);

    const auditInput = Array.isArray(input) ? undefined : input;
    const completedItemIds =
      Array.isArray(input)
        ? input
        : input.completedItemIds ||
          [
            input.markers?.foodProtection?.detected ? 'HY001' : undefined,
            input.markers?.cleanSurface?.detected ? 'HY002' : undefined,
            input.markers?.potableWater?.detected ? 'HY004' : undefined,
            input.markers?.coveredWasteBin?.detected ? 'HY005' : undefined,
          ].filter((id): id is string => Boolean(id));

    // Reject arbitrary checklist IDs that were not generated by the server
    for (const id of completedItemIds) {
      if (!VALID_HYGIENE_ITEM_IDS.has(id)) {
        throw AppError.badRequest(
          `Invalid checklist item ID: '${id}'. Only server-generated IDs are accepted.`
        );
      }
    }

    const checklist = getHygieneChecklistForBusiness(
      application.businessDetails?.stallType
    );

    const completedSet = new Set(completedItemIds);
    const mappedItems = checklist.map((item) => ({
      id: item.id,
      title: item.title,
      description: item.description,
      compliant: completedSet.has(item.id),
      mandatory: item.mandatory,
    }));

    const score = Math.round((completedItemIds.length / checklist.length) * 100);

    application.hygieneChecklist = {
      overallScore: score,
      isPrototype: true,
      completedItems: completedItemIds,
      items: mappedItems,
      generatedAt: new Date(),
    };

    if (auditInput?.markers || auditInput?.passed !== undefined) {
      application.hygieneAudit = {
        passed: Boolean(auditInput?.passed),
        confidenceScore: auditInput?.confidenceScore ?? score,
        markers: auditInput?.markers,
        summary: auditInput?.summary,
        verifiedAt: new Date(),
        isVerified: Boolean(auditInput?.passed),
      };
    }

    // Transition status to HYGIENE_GENERATED
    application.status = 'HYGIENE_GENERATED';
    await application.save();

    return {
      applicationId: application._id.toString(),
      status: application.status,
      overallScore: score,
      completedItems: completedItemIds,
      hygieneAudit: application.hygieneAudit,
      isPrototype: true,
    };
  }

  /**
   * Save confirmed synthetic demo document
   */
  static async saveSyntheticDocument(
    application: IApplication,
    input: UploadDocumentInput
  ) {
    this.verifyEligibilityChecked(application);

    // Validate size limit (5MB)
    const MAX_SIZE_BYTES = 5 * 1024 * 1024;
    let size = input.fileSizeBytes || 0;
    if (!size && input.fileData) {
      // Estimate from base64 string length
      size = Math.round((input.fileData.length * 3) / 4);
    }

    if (size > MAX_SIZE_BYTES) {
      throw AppError.badRequest('Oversized document. Maximum allowed file size is 5MB.');
    }

    const refNumber = `SYN-DOC-${Date.now().toString().slice(-6)}-${Math.floor(
      1000 + Math.random() * 9000
    )}`;

    application.syntheticDocument = {
      applicationRefNumber: refNumber,
      formType: 'FORM_A_SYNTHETIC',
      documentTitle: input.documentTitle || 'Synthetic Food Stall Premise Photo',
      documentData: input.fileData || input.fileUrl,
      mimeType: input.mimeType,
      fileSize: size,
      isSynthetic: true,
      generatedAt: new Date(),
    };

    application.documents.push({
      documentType: input.documentType,
      fileName: input.fileName || input.documentTitle,
      fileUrl: input.fileUrl || 'mock_storage_url',
      status: 'VERIFIED',
      uploadedAt: new Date(),
    });
    application.documentsVerified = true;

    // Maintain at least HYGIENE_GENERATED state
    if (application.status === 'ELIGIBILITY_CHECKED') {
      application.status = 'HYGIENE_GENERATED';
    }

    await application.save();

    return {
      applicationId: application._id.toString(),
      status: application.status,
      application,
      document: {
        applicationRefNumber: refNumber,
        documentTitle: application.syntheticDocument.documentTitle,
        mimeType: application.syntheticDocument.mimeType,
        isSynthetic: true,
        generatedAt: application.syntheticDocument.generatedAt,
      },
    };
  }
}
